/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 0481b2c954dd09c2cbb8d9e30a1c5d08)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	SITE_URL: "https://0xnefertt.github.io";
	GITHUB_REPOSITORY: "0xnefertt/0xnefertt.github.io";
	GITHUB_BRANCH: "main";
	OWNER_ID: "170924802";
	GITHUB_CLIENT_ID: "Ov23ctl29BzkDWDPKL6t";
	GITHUB_CLIENT_SECRET: string;
	SESSION_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SITE_URL" | "GITHUB_REPOSITORY" | "GITHUB_BRANCH" | "OWNER_ID" | "GITHUB_CLIENT_ID" | "GITHUB_CLIENT_SECRET" | "SESSION_SECRET">> {}
}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}